name: Foo pull-request workflow
on:
  pull_request:
    paths:
    - 'foo/*'

jobs:
  build:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'Great pull-request on this fine day:' $(date)
      - name: Create file
        env:
          super_secret: ${{ secrets.SUPER_SECRET }}
        run: "echo \"${super_secret^}\" "